---
title: "Análise de sequência para monitoramento e avaliação de impacto social"
author: "Ronaldo Baltar e Cláudia S. Baltar"
format:
  html: default
  docx: default
lang: pt-BR
bibliography: references.bib
filters:
  - wordcount
wordcount:
  count-code-blocks: false
  count-inline-code: false
---

Total de {{wordcount}} de 8.000 palavras já escritas.


# Introdução
com definição clara do problema, objeto ou experiência investigada;

A RBAVAL respeita o estilo e a criatividade dos autores para a composição do texto, mas recomenda que os manuscritos dos artigos originais, ensaios e relatos de experiências contenham elementos convencionais tais como: (a) introdução,  (b) método: (c)  (e)  considerações finais: apontando aprendizados, usos, desdobramentos, limitações e efeitos da avaliação ou pesquisa em questão.



# Método
descritos de forma objetiva e clara, de modo a permitir a melhor compreensão possível do percurso de investigação e sua eventual reprodução; 

# Resultados
resultados e discussão, que podem ser apresentados juntos ou separados;

# Considerações finais

Inserir citação do Zotero. [@gabadinho2011]
